import { test, expect } from '@playwright/test';
test('Board settings, Lanes, labels, comments, resources and Intake work through the Web', async ({
  page,
}) => {
  await page.goto('/login');
  await page.getByRole('link', { name: '使用飞书登录' }).click();
  await page.locator('select[name=user]').selectOption('user_a');
  await page.getByRole('button', { name: '授权登录' }).click();
  await page.waitForURL('**/my');
  await page.goto('/workspaces/beta/boards');
  await page.getByRole('button', { name: '新建看板', exact: true }).click();
  await page.getByLabel('名称', { exact: true }).fill('管理回归');
  await page.getByLabel('任务前缀').fill('MGMT');
  await page.getByLabel('模板').selectOption('core.project');
  await page.getByLabel('访问模式').selectOption('restricted');
  await page.getByRole('button', { name: '创建看板', exact: true }).click();
  await page.waitForURL('**/boards/MGMT');
  await page.getByRole('button', { name: '管理看板', exact: true }).click();
  await page.getByRole('checkbox', { name: '启用需求入口' }).check();
  await page.getByRole('dialog').getByRole('button', { name: '保存', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: '泳道', exact: true }).click();
  await page.getByPlaceholder('新泳道名称').fill('测试泳道');
  await page.getByRole('dialog').getByRole('button', { name: '添加', exact: true }).click();
  await expect(page.getByRole('textbox', { name: '测试泳道名称' })).toBeVisible();
  await page.getByRole('button', { name: '关闭', exact: true }).click();
  await page.getByRole('button', { name: '管理看板', exact: true }).click();
  await page.getByRole('button', { name: '标签与里程碑', exact: true }).click();
  await page.getByRole('textbox', { name: '新标签名称' }).fill('回归');
  await page.getByRole('button', { name: '添加标签', exact: true }).click();
  await expect(page.locator('.metadata-values')).toContainText('回归');
  await page.getByRole('button', { name: '关闭', exact: true }).click();
  await page.getByRole('button', { name: '新建任务', exact: true }).click();
  await page.getByLabel('标题', { exact: true }).fill('管理用任务');
  await page.getByRole('button', { name: '创建任务', exact: true }).click();
  await page.getByRole('button', { name: '管理用任务', exact: true }).click();
  await page.getByText('更多属性', { exact: true }).click();
  await page.getByRole('checkbox', { name: '回归', exact: true }).check();
  await page.getByRole('textbox', { name: '评论内容' }).fill('验收记录');
  await page.getByRole('button', { name: '发送评论' }).click();
  await expect(page.locator('.comments')).toContainText('验收记录');
  await page.getByPlaceholder('标题', { exact: true }).fill('验收链接');
  await page.getByPlaceholder('https://…', { exact: true }).fill('https://example.com/acceptance');
  await page.getByRole('button', { name: '添加链接' }).click();
  await expect(page.getByRole('link', { name: '验收链接' })).toBeVisible();
  await page.getByRole('button', { name: '关闭任务', exact: true }).click();
  await page.getByRole('button', { name: '需求', exact: true }).click();
  await page.getByLabel('需求标题').fill('待接受需求');
  await page.getByRole('button', { name: '提交需求', exact: true }).click();
  await expect(page.locator('.intake-list')).toContainText('待接受需求');
  await page.getByRole('button', { name: '接受并创建任务', exact: true }).click();
  await expect(page.locator('.intake-list')).toContainText('已接受');
  await page.getByRole('button', { name: '关闭', exact: true }).click();
  await expect(page.getByRole('button', { name: '待接受需求', exact: true })).toBeVisible();
});
