
CREATE TABLE rnd_system(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id uuid NOT NULL REFERENCES workspace,board_id uuid NOT NULL,name text NOT NULL,version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(id,board_id,workspace_id),UNIQUE(board_id,name),FOREIGN KEY(board_id,workspace_id) REFERENCES board(id,workspace_id));
CREATE TABLE rnd_module(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id uuid NOT NULL,board_id uuid NOT NULL,system_id uuid NOT NULL,name text NOT NULL,version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(id,board_id,workspace_id),UNIQUE(id,system_id,board_id,workspace_id),UNIQUE(system_id,name),FOREIGN KEY(system_id,board_id,workspace_id) REFERENCES rnd_system(id,board_id,workspace_id),FOREIGN KEY(board_id,workspace_id) REFERENCES board(id,workspace_id));
CREATE TABLE rnd_task_ext(task_id uuid PRIMARY KEY,workspace_id uuid NOT NULL,board_id uuid NOT NULL,system_id uuid,module_id uuid,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(task_id,board_id,workspace_id) REFERENCES task(id,board_id,workspace_id),FOREIGN KEY(system_id,board_id,workspace_id) REFERENCES rnd_system(id,board_id,workspace_id),FOREIGN KEY(module_id,board_id,workspace_id) REFERENCES rnd_module(id,board_id,workspace_id),FOREIGN KEY(module_id,system_id,board_id,workspace_id) REFERENCES rnd_module(id,system_id,board_id,workspace_id),CHECK(module_id IS NULL OR system_id IS NOT NULL));
CREATE TABLE rnd_lane_ext(lane_id uuid PRIMARY KEY,workspace_id uuid NOT NULL,board_id uuid NOT NULL,project_code text,owner_id uuid REFERENCES app_user,start_date date,target_end_date date,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(lane_id,board_id) REFERENCES board_lane(id,board_id),FOREIGN KEY(board_id,workspace_id) REFERENCES board(id,workspace_id));
CREATE FUNCTION set_rnd_task_fields(tid uuid,expected integer,p jsonb) RETURNS task LANGUAGE plpgsql AS $$DECLARE t task;BEGIN
 t:=require_task_edit(tid,expected);PERFORM require_plugin_enabled(t.workspace_id,'rnd');IF NOT EXISTS(SELECT 1 FROM board WHERE id=t.board_id AND plugin_key='rnd') THEN PERFORM raise_app_error('VALIDATION_FAILED');END IF;
 INSERT INTO rnd_task_ext(task_id,workspace_id,board_id) VALUES(tid,t.workspace_id,t.board_id) ON CONFLICT DO NOTHING;
 UPDATE rnd_task_ext SET system_id=CASE WHEN p?'system_id' THEN (p->>'system_id')::uuid ELSE system_id END,module_id=CASE WHEN p?'module_id' THEN (p->>'module_id')::uuid ELSE module_id END,updated_at=now() WHERE task_id=tid;
 UPDATE task SET version=version+1,last_activity_at=now() WHERE id=tid RETURNING * INTO t;RETURN t;END$$;
