
CREATE TABLE intake_request(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id uuid NOT NULL,board_id uuid NOT NULL,requester_id uuid NOT NULL REFERENCES app_user,title text NOT NULL CHECK(char_length(trim(title)) BETWEEN 1 AND 255),description text,expected_date date,status text NOT NULL DEFAULT 'pending' CHECK(status IN('pending','accepted','declined')),reason text,task_id uuid,client_mutation_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(requester_id,client_mutation_id),FOREIGN KEY(board_id,workspace_id) REFERENCES board(id,workspace_id),FOREIGN KEY(task_id,board_id,workspace_id) REFERENCES task(id,board_id,workspace_id));
CREATE TABLE notification(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES app_user,workspace_id uuid REFERENCES workspace,type text NOT NULL,entity_type text NOT NULL,entity_id uuid NOT NULL,payload jsonb NOT NULL DEFAULT '{}',read_at timestamptz,dedupe_key text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX notification_dedupe ON notification(user_id,dedupe_key) WHERE dedupe_key IS NOT NULL;
CREATE INDEX notification_user ON notification(user_id,created_at DESC);
CREATE FUNCTION task_assignment_notification() RETURNS trigger LANGUAGE plpgsql AS $$DECLARE t task;uid uuid;BEGIN
 IF TG_TABLE_NAME='task_participant' THEN SELECT * INTO t FROM task WHERE id=NEW.task_id;uid:=NEW.user_id;ELSE t:=NEW;uid:=NEW.responsible_id;IF TG_OP='UPDATE' AND NEW.responsible_id=OLD.responsible_id THEN RETURN NULL;END IF;END IF;
 IF uid IS DISTINCT FROM actor_id() THEN INSERT INTO notification(user_id,workspace_id,type,entity_type,entity_id,dedupe_key) VALUES(uid,t.workspace_id,CASE WHEN TG_TABLE_NAME='task_participant' THEN 'task.participant' ELSE 'task.responsible' END,'task',t.id,t.id::text||':'||t.version::text||':'||uid::text||':'||TG_TABLE_NAME) ON CONFLICT DO NOTHING;END IF;RETURN NULL;END$$;
CREATE TRIGGER assignment_notification AFTER INSERT OR UPDATE ON task FOR EACH ROW EXECUTE FUNCTION task_assignment_notification();
CREATE TRIGGER participation_notification AFTER INSERT ON task_participant FOR EACH ROW EXECUTE FUNCTION task_assignment_notification();
CREATE FUNCTION create_intake(bid uuid,p jsonb) RETURNS intake_request LANGUAGE plpgsql AS $$DECLARE b board;r intake_request;BEGIN SELECT * INTO b FROM board WHERE id=bid;PERFORM lock_workspace(b.workspace_id);PERFORM lock_board(bid);IF NOT can_read_board(actor_id(),bid) OR NOT b.intake_enabled THEN PERFORM raise_app_error('FORBIDDEN');END IF;
 INSERT INTO intake_request(workspace_id,board_id,requester_id,title,description,expected_date,client_mutation_id) VALUES(b.workspace_id,bid,actor_id(),p->>'title',p->>'description',(p->>'expectedDate')::date,(p->>'clientMutationId')::uuid) ON CONFLICT(requester_id,client_mutation_id) DO NOTHING RETURNING * INTO r;
 IF r.id IS NULL THEN SELECT * INTO r FROM intake_request WHERE requester_id=actor_id() AND client_mutation_id=(p->>'clientMutationId')::uuid;END IF;RETURN r;END$$;
CREATE FUNCTION decide_intake(rid uuid,p_accept boolean,p jsonb) RETURNS intake_request LANGUAGE plpgsql AS $$DECLARE r intake_request;t task;wid uuid;bid uuid;BEGIN SELECT workspace_id,board_id INTO wid,bid FROM intake_request WHERE id=rid;IF bid IS NULL THEN PERFORM raise_app_error('NOT_FOUND');END IF;PERFORM lock_workspace(wid);PERFORM lock_board(bid,true);PERFORM require_board_manage(bid);SELECT * INTO r FROM intake_request WHERE id=rid FOR UPDATE;IF r.status<>'pending' THEN RETURN r;END IF;
 IF p_accept THEN t:=create_task(bid,p||jsonb_build_object('title',r.title,'descriptionText',r.description,'requesterId',r.requester_id,'dueDate',r.expected_date,'clientMutationId',r.client_mutation_id));UPDATE intake_request SET status='accepted',task_id=t.id,updated_at=now() WHERE id=rid RETURNING * INTO r;
 ELSE UPDATE intake_request SET status='declined',reason=p->>'reason',updated_at=now() WHERE id=rid RETURNING * INTO r;END IF;RETURN r;END$$;
CREATE FUNCTION audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$DECLARE old_j jsonb;new_j jsonb;row_j jsonb;wid uuid;eid uuid;BEGIN
 old_j:=CASE WHEN TG_OP='INSERT' THEN NULL ELSE to_jsonb(OLD) END;new_j:=CASE WHEN TG_OP='DELETE' THEN NULL ELSE to_jsonb(NEW) END;row_j:=coalesce(new_j,old_j);
 IF TG_TABLE_NAME='workspace' THEN wid:=(row_j->>'id')::uuid;ELSE wid:=(row_j->>'workspace_id')::uuid;END IF;
 IF wid IS NULL AND row_j?'board_id' THEN SELECT workspace_id INTO wid FROM board WHERE id=(row_j->>'board_id')::uuid;END IF;
 eid:=coalesce((row_j->>'id')::uuid,(row_j->>'task_id')::uuid,(row_j->>'user_id')::uuid,(row_j->>'lane_id')::uuid,wid);
 INSERT INTO audit_log(workspace_id,actor_id,action,entity_type,entity_id,before,after,request_id) VALUES(wid,actor_id(),lower(TG_OP),TG_TABLE_NAME,eid,old_j,new_j,nullif(current_setting('app.request_id',true),''));RETURN NULL;END$$;
DO $$DECLARE tbl text;BEGIN FOREACH tbl IN ARRAY ARRAY['app_user','workspace','workspace_member','workspace_plugin','board','board_member','board_lane','board_state','intake_request','rnd_system','rnd_module','rnd_lane_ext','ops_service','ops_lane_ext'] LOOP EXECUTE format('CREATE TRIGGER audit_write AFTER INSERT OR UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION audit_mutation()',tbl);END LOOP;END$$;
-- Database is server-only. Supabase's browser-facing roles get no business table or function grants.
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM PUBLIC;
DO $$DECLARE r text;BEGIN FOREACH r IN ARRAY ARRAY['anon','authenticated'] LOOP IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname=r) THEN EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA public FROM %I',r);EXECUTE format('REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM %I',r);END IF;END LOOP;END$$;
