
CREATE TABLE ops_service(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id uuid NOT NULL,board_id uuid NOT NULL,name text NOT NULL,version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(id,board_id,workspace_id),UNIQUE(board_id,name),FOREIGN KEY(board_id,workspace_id) REFERENCES board(id,workspace_id));
CREATE TABLE ops_task_ext(task_id uuid PRIMARY KEY,workspace_id uuid NOT NULL,board_id uuid NOT NULL,severity text CHECK(severity IN('P1','P2','P3','P4')),impact text,detected_at timestamptz,recovered_at timestamptz,service_id uuid,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(task_id,board_id,workspace_id) REFERENCES task(id,board_id,workspace_id),FOREIGN KEY(service_id,board_id,workspace_id) REFERENCES ops_service(id,board_id,workspace_id));
CREATE TABLE ops_lane_ext(lane_id uuid PRIMARY KEY,workspace_id uuid NOT NULL,board_id uuid NOT NULL,service_id uuid,description text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(lane_id,board_id) REFERENCES board_lane(id,board_id),FOREIGN KEY(board_id,workspace_id) REFERENCES board(id,workspace_id),FOREIGN KEY(service_id,board_id,workspace_id) REFERENCES ops_service(id,board_id,workspace_id));
CREATE FUNCTION set_ops_task_fields(tid uuid,expected integer,p jsonb) RETURNS task LANGUAGE plpgsql AS $$DECLARE t task;BEGIN
 t:=require_task_edit(tid,expected);PERFORM require_plugin_enabled(t.workspace_id,'ops');IF NOT EXISTS(SELECT 1 FROM board WHERE id=t.board_id AND plugin_key='ops') THEN PERFORM raise_app_error('VALIDATION_FAILED');END IF;
 INSERT INTO ops_task_ext(task_id,workspace_id,board_id) VALUES(tid,t.workspace_id,t.board_id) ON CONFLICT DO NOTHING;
 UPDATE ops_task_ext SET severity=CASE WHEN p?'severity' THEN p->>'severity' ELSE severity END,impact=CASE WHEN p?'impact' THEN p->>'impact' ELSE impact END,detected_at=CASE WHEN p?'detected_at' THEN (p->>'detected_at')::timestamptz ELSE detected_at END,recovered_at=CASE WHEN p?'recovered_at' THEN (p->>'recovered_at')::timestamptz ELSE recovered_at END,service_id=CASE WHEN p?'service_id' THEN (p->>'service_id')::uuid ELSE service_id END,updated_at=now() WHERE task_id=tid;
 UPDATE task SET version=version+1,last_activity_at=now() WHERE id=tid RETURNING * INTO t;RETURN t;END$$;
CREATE OR REPLACE FUNCTION task_plugin_fields(tid uuid) RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT coalesce((SELECT to_jsonb(r)-'task_id'-'workspace_id'-'board_id'-'created_at'-'updated_at' FROM rnd_task_ext r JOIN task t ON t.id=r.task_id JOIN workspace_plugin p ON p.workspace_id=t.workspace_id AND p.plugin_key='rnd' WHERE r.task_id=tid),(SELECT to_jsonb(o)-'task_id'-'workspace_id'-'board_id'-'created_at'-'updated_at' FROM ops_task_ext o JOIN task t ON t.id=o.task_id JOIN workspace_plugin p ON p.workspace_id=t.workspace_id AND p.plugin_key='ops' WHERE o.task_id=tid),'{}'::jsonb)$$;
